services:
  mongo: # New MongoDB service
    image: mongo:latest
    container_name: capivale_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: capivale_backend
    command: npm start
    
    ports:
      - "3001:3001"
    depends_on:
      - mongo # Changed from postgres
    environment:
      - NODE_ENV=production
      - PORT=3001
      - MONGO_URI=mongodb://mongo:27017/capivale_db # Changed to MONGO_URI
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: capivale_frontend
    command: npm run dev
    
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=http://localhost:3001/api
    restart: unless-stopped

volumes:
  mongo_data: # New MongoDB volume
